from __future__ import annotations

from typing import Protocol

from contracts.events import ExecutionLimits, QueuedEvent
from contracts.read_views import ComponentPatch
from contracts.turn import CompiledSchedule, GameCommand, ProtocolSnapshot, TurnOutcome, TurnPublication
from domain.canonical import JsonObject, JsonValue
from domain.primitives import ComponentAddress, EntityId, FieldAddress, FieldFamily, FrozenPayload, TypeKey
from domain.state_types import ComponentRecord, CoreSnapshot, PendingDocument, SimulationPins


class ComponentCodec(Protocol):
    @property
    def schema(self) -> TypeKey: ...
    def decode(self, entity_id: EntityId, fields: JsonObject) -> ComponentRecord: ...
    def encode(self, record: ComponentRecord) -> JsonObject: ...


class PatchRoute(Protocol):
    @property
    def schema(self) -> TypeKey: ...
    @property
    def component_schema(self) -> TypeKey: ...
    @property
    def family(self) -> FieldFamily: ...
    def apply(self, before: ComponentRecord, patch: ComponentPatch) -> ComponentRecord: ...


class CheckpointPolicy(Protocol):
    def validate(self, core: CoreSnapshot, protocol: ProtocolSnapshot) -> None: ...


class StateIO(Protocol):
    @property
    def execution_limits(self) -> ExecutionLimits: ...
    def encode_pending(self, event: QueuedEvent) -> PendingDocument: ...
    def decode_pending(self, document: PendingDocument) -> QueuedEvent: ...
    @property
    def pins(self) -> SimulationPins: ...
    @property
    def schedule(self) -> CompiledSchedule: ...
    def validate_checkpoint(self, core: CoreSnapshot, protocol: ProtocolSnapshot) -> None: ...
    def encode_core(self, core: CoreSnapshot) -> JsonObject: ...
    def decode_core(self, document: JsonObject) -> CoreSnapshot: ...
    def hash_core(self, core: CoreSnapshot) -> str: ...
    def encode_payload(self, payload: FrozenPayload) -> JsonObject: ...
    def encode_command(self, command: GameCommand) -> JsonObject: ...
    def decode_command(self, document: JsonObject) -> GameCommand: ...
    def encode_protocol(self, protocol: ProtocolSnapshot) -> JsonObject: ...
    def decode_protocol(self, document: JsonObject, core: CoreSnapshot) -> ProtocolSnapshot: ...
    def encode_publication(self, publication: TurnPublication) -> JsonObject: ...
    def decode_outcome(self, document: JsonObject) -> TurnOutcome: ...
    def validate_effects(self, command: GameCommand, outcome: TurnOutcome, core: CoreSnapshot,
                         protocol: ProtocolSnapshot, facts: JsonValue, diff: JsonValue) -> None: ...
    def apply_patch(self, address: ComponentAddress, allowed: FieldAddress,
                    before: ComponentRecord, patch: ComponentPatch) -> ComponentRecord: ...
